name: "Build and publish binaries"

permissions:
  contents: write

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - run: pip install pyinstaller
    - run: pyinstaller --noconsole --onefile --distpath ./dist/${{ runner.os }} src/FarmUpload.py
    #- uses: actions/upload-artifact@v4
    #  with:
    #    path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*/FarmUpload*
